### PR TITLE
Rewrite DB

### PR DESCRIPTION
**Pull request by DaMatrix**

### CODE REVIEW

**Comment by NycuRO** [comment]
May i purpose you to use hikari? :D

**Comment by DaMatrix** [comment]
use what?

**Comment by NycuRO** [comment]
HikariCP. https://github.com/brettwooldridge/HikariCP

**Comment by DaMatrix** [comment]
this has nothing to to with sql in the slightest lol

**Comment by NycuRO** [comment]
GG!

**Comment by DaMatrix** [comment]
it's in #8 now lol

**Pull request closed without merging**
